### ISSUE TITLE
Prefer stateless functions when only props are used

### ISSUE THREAD

**Issue by kaisermann** [vtex/javascript#22]
**What is to be discussed?**

ESLint rule: `prefer-stateless-function`

**Invalid:**
```jsx
class Foo extends React.Component {
  render() {
    if (!this.props.foo) {
      return null
    }
    return <div>{this.props.foo}</div>;
  }
}
```

The following pattern is not considered a warning:

**Valid:**
```jsx
const Foo = function(props, context) {
  const {
    location
  } = context.router;

  return <div>{props.foo}</div>;
};
```

This rule is currently `off` for us.

**Describe the solution you'd like**

If no state is used, i don't see why someone would/should use a class.

**Additional context**

Rule documentation: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-stateless-function.md

**Comment by guilhermebruzzi** [comment]
On the past we used the lifecycles of React a lot and only classes were, so many people including @klzns and even kentcdodds (had an article) preferred to create an Class so that diffs on PRs are easier than to transform a function to a class.

Now with hooks, I think we could turn on this rule.

But just to be more clear, this rule doesn't only check if the component only uses props, right? If it uses any lifecycle (`shouldComponentUpdate`, `componentDidMount`, etc) it will not throw a warning, right? (inStore because of redux uses an small amount of state inside React Components)

**Comment by kaisermann** [comment]
@guilhermebruzzi It doesn't flag it if you're using lifecycle methods!
