### ISSUE TITLE
Create monorepo of front-end lint/format configs.

### ISSUE THREAD

**Issue by kaisermann** [vtex/javascript#7]
~We currently maintain two `eslint` config packages: `eslint-config-vtex` and `eslint-config-vtex-react`. There's really no useful advantage for keeping those two separated. We should unify those projects and keep maintaining only `eslint-config-vtex`.~

~I still don't know if the `react` part of it should be turned `on` by default or not. We can work around this by creating a `react.js` file and, when extending the config, use `eslint-config-vtex/react` instead of just `eslint-config-vtex`~

We want to keep our lint and format packages separate, but living inside a single repo for ease of maintainability.

https://gihub.com/vtex/javascript

**Comment by lucasecdb** [comment]
I think the reason to have a separate eslint config for react projects is the need to have `react` as a peer dependency. If you have a node app but want to have all the tooling and opinionated rules that exists in our eslint configuration, it makes no sense to install react in the project just so we can satisfy the peer dependencies of the shared eslint config.

IMHO it's unnecessary to try unify those two configs. Since the `eslint-config-vtex-react` already extends the base `eslint-config-vtex`, the package only contains the rules that are specific for react projects, plus all the rules defined in the base configuration. When you have a react project, you only really need to install the `eslint-config-vtex-react` package.

We are basically doing the same as AirBnb's `eslint-config-airbnb-base` and `eslint-config-airbnb`, but with different names.

**Comment by kaisermann** [comment]
I understand your point and it would be completely valid if `react` was a peer dep of  `eslint-config-react`, which is not the case: https://github.com/yannickcr/eslint-plugin-react/blob/master/package.json#L55.

**Comment by kaisermann** [comment]
A valid point would be that even for a `node` project you would be downloading the rules for a `react` project. Usually, tooling size is not the most emergent concern here, but I just checked the total size of always installing `eslint-plugin-react`, `eslint-plugin-react-hooks`, `eslint-config-react` and `eslint-plugin-jsx-a11y`: 5.1  + 280 + 19.8 + 203.2 = **508.1kb**

_That_ is 508 kb of definitely unnecessary weight for a `node` project.

**Comment by lucasecdb** [comment]
oh, nice! I don't know why I thought that it was a peer dependency. Must have mixed up some things :sweat_smile:

**Comment by kaisermann** [comment]
Me and @lucasecdb have talked about keeping the two packages separate but living inside a monorepo, maybe together with our `prettier-config` and `tsconfig`.

**Comment by kaisermann** [comment]
Shopify takes a different approach for handling multiple eslint configs: https://github.com/Shopify/eslint-plugin-shopify

It uses a eslint plugin which holds not only custom rule presets but custom rules as well. It's a single package, so it has the dependency size problem, but it's a battery-included project for many kinds of scenarios.

![image](https://user-images.githubusercontent.com/12702016/72992936-50ba4580-3dd3-11ea-9e35-64f030dcb72f.png)

Installing our `eslint-config-vtex`:
![image](https://user-images.githubusercontent.com/12702016/72993022-72b3c800-3dd3-11ea-873d-71d941adaba1.png)

Installing our `eslint-config-vtex-react`:
![image](https://user-images.githubusercontent.com/12702016/72992991-6465ac00-3dd3-11ea-8530-9dff08d929f0.png)

Certainly a few MBs (ouch) heavier, but I like the idea of a plugin concentrating all the configs _and_ custom rules. There's the point that extending a config from a plugin is a little more verbose:

`"extends": ["plugin:vtex"]` instead of `"extends": ["vtex"]`

But it allows us to have separate configs, such as what was suggested in the original post: `"extends": ["plugin:vtex", "plugin:vtex/react"]`.

Anyway, I think what I liked the most is the possibility of having custom rules, so we don't necessarily need to follow the same path. We can have a `eslint-plugin-vtex` for custom rules if we want and add it to the `eslint-config-vtex`
